### PR TITLE
BRING BACK JQUERY and make things prettier (no offense Josh)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mrled** [comment]
Vote no merge until better commit messages are provided

**Comment by mrled** [comment]
MAKE JQUERY GREAT AGAIN jk lol jquery suxxxx

**Comment by ghost** [comment]
@mrled We don't need your negativity, or frankly any of your opinions here, kthxbye

**Comment by mrled** [comment]
jQuery needs more negativity in its life I think

**Pull request merged**
