### PR TITLE
OMG*FAP*FAP*FAP*FAP*

### PR DESCRIPTION
**Pull request by mauvehed**

### CODE REVIEW

**Comment by mrled** [comment]
-1 too many ponies

**Comment by ghost** [comment]
-10
Why would you do something like this?!? Do you think this is JUST FOR FUN?!?
Useful contributions only, plz! Geeeeeeezeee

**Comment by ledbetterljoshua** [comment]
If anything we need to somehow incorporate the images into the actual project. No need for unused images in the img folder.

**Comment by hannahlindsley** [comment]
I don't see the machine learning in this??

**Comment by mrled** [comment]
THIS MACHINE HAS LEARNED: NOTHING

**Pull request closed without merging**
