### PR TITLE
Make a kinda ugly thing.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mrled** [comment]
Hey before merging this, I think we should have a quick 5-6 month conversation debating the relative merits of using jQuery in one-off joke applications written to annoy friends

**Comment by ledbetterljoshua** [comment]
lol the jQuery is only being used for the injection of the text. I think we can do that without jQuery, but yeah, at least 6 months

**Comment by ghost** [comment]
Look..... I was looking forward to future features, for which jQuery may be useful, okay? I have big plans for this, you guys. Big plans.

**Comment by ledbetterljoshua** [comment]
Lmao. Its merged

**Pull request merged**
